name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    uses: finsweet/workflow-release/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  purge-jsdelivr-cache:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get package info and purge jsDelivr cache
        run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          PACKAGE_VERSION=$(jq -r .version package.json)
          MAJOR_VERSION=$(echo $PACKAGE_VERSION | cut -d. -f1)
          echo "Purging jsDelivr cache for ${PACKAGE_NAME}"
          curl -X GET "https://purge.jsdelivr.net/npm/${PACKAGE_NAME}"
          echo "Purging jsDelivr cache for ${PACKAGE_NAME}@latest"
          curl -X GET "https://purge.jsdelivr.net/npm/${PACKAGE_NAME}@latest"
          echo "Purging jsDelivr cache for ${PACKAGE_NAME}@${MAJOR_VERSION}"
          curl -X GET "https://purge.jsdelivr.net/npm/${PACKAGE_NAME}@${MAJOR_VERSION}"
